services:
  postgres:
    image: postgres:15-alpine
    container_name: mongez_postgres
    environment:
      POSTGRES_USER: mongez
      POSTGRES_PASSWORD: mongezpassword
      POSTGRES_DB: mongez_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mongez_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: