services:
  postgres:
    image: postgres:15-alpine
    container_name: mongez_postgres
    environment:
      POSTGRES_USER: mongez
      POSTGRES_PASSWORD: mongezpassword
      POSTGRES_DB: mongez_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mongez_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: mongez_qdrant
    ports:
      - "6333:6333"    # REST API — used by Python AI service
      - "6334:6334"    # gRPC — optional, faster for bulk operations
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # ai-service:
  #   build:
  #     context: ../ai-service
  #     dockerfile: Dockerfile
  #   container_name: mongez_ai
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env                           # Contains GROQ_API_KEY etc.
  #   environment:
  #     - NESTJS_BASE_URL=http://host.docker.internal:3000  # NestJS on host
  #     - QDRANT_URL=http://qdrant:6333
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - qdrant
  #     - redis
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  qdrant_data: